import os
from typing import TypedDict
from dotenv import load_dotenv
from langgraph.graph import StateGraph, END

# Import your existing agents and tools
from stock_agent import analyze_stocks
from ipo_agent import analyze_ipos
from twilio.rest import Client

# Load environment variables
load_dotenv()

# 1. Define the "State"
# This is like a shared clipboard that gets passed between steps.
class AgentState(TypedDict):
    stock_report: str
    ipo_report: str
    final_message: str

# 2. Define the Nodes (The actual work steps)

def fetch_stock_data(state: AgentState):
    print("--- NODE: Fetching Stocks ---")
    # Calls your stock_agent logic
    result = analyze_stocks() 
    return {"stock_report": result}

def fetch_ipo_data(state: AgentState):
    print("--- NODE: Fetching IPOs ---")
    # Calls your ipo_agent logic
    result = analyze_ipos()
    return {"ipo_report": result}

def combine_and_send(state: AgentState):
    print("--- NODE: Formatting & Sending WhatsApp ---")
    
    stock_text = state.get("stock_report", "No Stock Data Available.")
    ipo_text = state.get("ipo_report", "No IPO Data Available.")
    
    # Create a clean message header
    final_msg = f"📊 *Daily Market Insight* 📊\n\n{stock_text}\n\n{ipo_text}\n\n_Generated by your AI Agent_"
    
    # Send via Twilio
    sid = os.getenv("TWILIO_ACCOUNT_SID")
    token = os.getenv("TWILIO_AUTH_TOKEN")
    to_number = 'whatsapp:+919920713032' # <--- REPLACE THIS!

    client = Client(sid, token)
    message = client.messages.create(
        from_='whatsapp:+14155238886',
        body=final_msg,
        to=to_number
    )
    
    print(f"✅ Message sent! ID: {message.sid}")
    return {"final_message": final_msg}

# 3. Build the Graph (The Workflow)
workflow = StateGraph(AgentState)

# Add our nodes
workflow.add_node("get_stocks", fetch_stock_data)
workflow.add_node("get_ipos", fetch_ipo_data)
workflow.add_node("send_whatsapp", combine_and_send)

# Define the path: Start -> Stocks -> IPOs -> WhatsApp -> End
workflow.set_entry_point("get_stocks")
workflow.add_edge("get_stocks", "get_ipos")
workflow.add_edge("get_ipos", "send_whatsapp")
workflow.add_edge("send_whatsapp", END)

# Compile the machine
app = workflow.compile()

# 4. Run the Application
if __name__ == "__main__":
    print("🚀 Starting AI Agent Workflow...")
    app.invoke({"stock_report": "", "ipo_report": "", "final_message": ""})